Premiere livraison
PaylinePaymentMethod/payment-method-sharegroop pull request #1
Opened 2019-12-02 09:39 UTC by JanFLORENT

2019-12-13 10:37 UTC, CharlelieBouvier requested changes

2019-12-13 10:37 UTC, CharlelieBouvier commented on build.gradle
> +    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.0'
Log4J core en testImplementation

2019-12-13 10:37 UTC, CharlelieBouvier commented on build.gradle
> +    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.11.0'
Log4J api en compileOnly

2019-12-13 10:37 UTC, CharlelieBouvier commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10-bin.zip
ce serait pas mal de passer à une version plus récente, comme 6.0.1 https://gradle.org/releases/

2019-12-13 10:37 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/sharegroop/service/impl/PaymentServiceImpl.java
> +        String templateScript = "ShareGroop.initCaptain({\n" +
Mettre ces chaînes en constantes

2019-12-13 10:37 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/sharegroop/service/impl/PaymentServiceImpl.java
> +                .withDisplayButton(false)
Comment on passe au step3 s'il n'y a pas de bouton?

2019-12-13 10:37 UTC, CharlelieBouvier commented on src/main/java/com/payline/payment/sharegroop/service/impl/PaymentServiceImpl.java
> +                .withDisplayButton(false)
On peut mettre le message d'email au dessus du Widget Sharegroop, en précisant la "description" du moyen de paiement

2019-12-16 14:17 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/PaymentServiceImpl.java
> +                .withDisplayButton(false)
effectivement, j'ai mis le message de la step2 en description de la step1 et ai fait passé la step3 en 2

2020-01-17 09:28 UTC, merged