Paylapmext 234 - Evolution de cinématique
PaylinePaymentMethod/payment-method-sharegroop pull request #5
Opened 2020-08-05 08:44 UTC by martin-grescu

Pas de changement dans les partner_conf. 

![image](https://user-images.githubusercontent.com/55979277/89391501-994ea600-d708-11ea-9377-f4027f5b4850.png)

2020-09-10 14:22 UTC, pesublet requested changes
Quelques retours

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/bean/notification/SharegroopNotificationResponse.java
> +    public static SharegroopNotificationResponse fromJson(String json ){ return new Gson().fromJson( json, SharegroopNotificationResponse.class ); }
Pourrais tu déplacer cette méthode dans un service ? je crois qu'Equens fait comme cela

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +    private static final String WEBHOOK_SECRET_KEY = "whsk_f19f3281-eb6f-4d5f-a378-8df1d32f6b91";
est ce une donnée variable suivant les environnement et un secret qui doit rester confidentiel ? si oui il faut déplacer cela dans le sensitivePartnerConfigurationMap par exemple

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +            LOGGER.error("Incorrect data - webhookSecretKey : {} - content : {} - signature : {}", webhookSecretKey,content,signature);
si la clé est confidentielle je pense qu'il ne faut pas la logguer

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/utils/PluginUtils.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8));
Il faut penser à fermer le flux

2020-09-10 14:22 UTC, pesublet commented on src/test/java/com/payline/payment/sharegroop/MockUtils.java
> +    private static final String WEBHOOK_SECRET_KEY = "whsk_f19f3281-eb6f-4d5f-a378-8df1d32f6b91";
ne pas remettre la vraie clé dans les tests si elle est confidentielle

2020-09-10 14:22 UTC, pesublet commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        Boolean flag = false;
tu n'es pas obligé d'initialiser le bool ici, tu peux le faire au moment de l'appel à la fonction à tester
`Boolean flag = service.verifySignature(MockUtils.getWebhookSecretKey(), content, signature);`

2020-09-10 14:22 UTC, pesublet commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        Boolean flag = false;
idem

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +            return "";
je ne suis pas fan du return "", il vaut mieux je pense logger l'erreur et throw une exception

2020-09-10 14:22 UTC, pesublet commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +
il manque un test OK sur hashMac() (même si il est testé indirectement par verifySignature(), cela reste plus lisible)

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +    public static String hashMac(String text, String secretKey) {
pourquoi cette méthode est elle static ?

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +    public static String toHexString(byte[] bytes) {
pourquoi cette méthode est elle static ?

2020-09-10 14:22 UTC, pesublet commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +            String signature = request.getHeaderInfos().get(SG_SIGNATURE);
ne jamais faire confiance à ce qui vient de l'extérieur ! il faut tester si signature est null ou non et logger cela si null.
Cela évite en effet d'avoir un NullPointerException dont on ne connait pas la cause une fois le plugin (mal) déployé

2020-09-10 14:22 UTC, pesublet commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        HashMap<String, String> headerInfo = new HashMap<>();
Map plutôt que HashMap, même si on est dans les tests :)

2020-09-10 14:22 UTC, pesublet commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        HashMap<String, String> headerInfo = new HashMap<>();
idem

2020-10-09 08:50 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/bean/notification/SharegroopNotificationResponse.java
> +    public static SharegroopNotificationResponse fromJson(String json ){ return new Gson().fromJson( json, SharegroopNotificationResponse.class ); }
fait, j'ai déplacé tous les fromJson() dans un service dédié

2020-10-09 09:08 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +            LOGGER.error("Incorrect data - webhookSecretKey : {} - content : {} - signature : {}", webhookSecretKey,content,signature);
effectivement... fait

2020-10-09 09:44 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +    private static final String WEBHOOK_SECRET_KEY = "whsk_f19f3281-eb6f-4d5f-a378-8df1d32f6b91";
Bien vu, je ne sais pas ce qu'il s'est passé, c'est déplacé dans la MapSensitive des PartnerConfig (et la doc est mise a jour )

2020-10-09 09:53 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/utils/PluginUtils.java
> +        BufferedReader br = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8));
fait

2020-10-09 10:02 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        Boolean flag = false;
fait

2020-10-09 10:02 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sharegroop/MockUtils.java
> +    private static final String WEBHOOK_SECRET_KEY = "whsk_f19f3281-eb6f-4d5f-a378-8df1d32f6b91";
fait

2020-10-09 10:03 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        Boolean flag = false;
fait

2020-10-09 12:26 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +            return "";
fait

2020-10-09 12:26 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +
fait

2020-10-09 12:27 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +    public static String hashMac(String text, String secretKey) {
fait

2020-10-09 12:27 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +    public static String toHexString(byte[] bytes) {
fait

2020-10-09 12:32 UTC, JanFLORENT commented on src/main/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImpl.java
> +            String signature = request.getHeaderInfos().get(SG_SIGNATURE);
fait

2020-10-09 12:34 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        HashMap<String, String> headerInfo = new HashMap<>();
oups... fait

2020-10-09 12:35 UTC, JanFLORENT commented on src/test/java/com/payline/payment/sharegroop/service/impl/NotificationServiceImplTest.java
> +        HashMap<String, String> headerInfo = new HashMap<>();
fait

2020-10-09 13:23 UTC, JanFLORENT commented
![image](https://user-images.githubusercontent.com/41673610/95588008-22ed5d80-0a43-11eb-9792-08bb6d2ca2eb.png)

Les partnerConf ont changé, voir: https://docs.monext.fr/pages/viewpage.action?pageId=748248689

2020-10-09 14:42 UTC, pesublet approved these changes

2020-10-09 14:42 UTC, merged